# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: session-dsm.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11session-dsm.proto\x12\x1c\x61\x63\x63\x65lbyte.session.sessiondsm\"R\n\x1bRequestTerminateGameSession\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x11\n\tnamespace\x18\x02 \x01(\t\x12\x0c\n\x04zone\x18\x03 \x01(\t\"f\n\x1cResponseTerminateGameSession\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x11\n\tnamespace\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12\x0e\n\x06reason\x18\x04 \x01(\t\"\xc8\x01\n\x18RequestCreateGameSession\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x11\n\tnamespace\x18\x02 \x01(\t\x12\x12\n\ndeployment\x18\x03 \x01(\t\x12\x14\n\x0csession_data\x18\x04 \x01(\t\x12\x18\n\x10requested_region\x18\x05 \x03(\t\x12\x16\n\x0emaximum_player\x18\x06 \x01(\x03\x12\x16\n\x0e\x63lient_version\x18\x07 \x01(\t\x12\x11\n\tgame_mode\x18\x08 \x01(\t\"\x8c\x02\n\x19ResponseCreateGameSession\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x11\n\tnamespace\x18\x02 \x01(\t\x12\x14\n\x0csession_data\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\n\n\x02ip\x18\x05 \x01(\t\x12\x0c\n\x04port\x18\x06 \x01(\x03\x12\x11\n\tserver_id\x18\x07 \x01(\t\x12\x0e\n\x06source\x18\x08 \x01(\t\x12\x12\n\ndeployment\x18\t \x01(\t\x12\x0e\n\x06region\x18\n \x01(\t\x12\x16\n\x0e\x63lient_version\x18\x0b \x01(\t\x12\x11\n\tgame_mode\x18\x0c \x01(\t\x12\x16\n\x0e\x63reated_region\x18\r \x01(\t2\xa3\x02\n\nSessionDsm\x12\x84\x01\n\x11\x43reateGameSession\x12\x36.accelbyte.session.sessiondsm.RequestCreateGameSession\x1a\x37.accelbyte.session.sessiondsm.ResponseCreateGameSession\x12\x8d\x01\n\x14TerminateGameSession\x12\x39.accelbyte.session.sessiondsm.RequestTerminateGameSession\x1a:.accelbyte.session.sessiondsm.ResponseTerminateGameSessionBe\n net.accelbyte.session.sessiondsmP\x01Z accelbyte.net/session/sessiondsm\xaa\x02\x1c\x41\x63\x63\x65lByte.Session.SessionDsmb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'session_dsm_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n net.accelbyte.session.sessiondsmP\001Z accelbyte.net/session/sessiondsm\252\002\034AccelByte.Session.SessionDsm'
  _REQUESTTERMINATEGAMESESSION._serialized_start=51
  _REQUESTTERMINATEGAMESESSION._serialized_end=133
  _RESPONSETERMINATEGAMESESSION._serialized_start=135
  _RESPONSETERMINATEGAMESESSION._serialized_end=237
  _REQUESTCREATEGAMESESSION._serialized_start=240
  _REQUESTCREATEGAMESESSION._serialized_end=440
  _RESPONSECREATEGAMESESSION._serialized_start=443
  _RESPONSECREATEGAMESESSION._serialized_end=711
  _SESSIONDSM._serialized_start=714
  _SESSIONDSM._serialized_end=1005
# @@protoc_insertion_point(module_scope)
