# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import session_dsm_pb2 as session__dsm__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in session_dsm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SessionDsmStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateGameSession = channel.unary_unary(
                '/accelbyte.session.sessiondsm.SessionDsm/CreateGameSession',
                request_serializer=session__dsm__pb2.RequestCreateGameSession.SerializeToString,
                response_deserializer=session__dsm__pb2.ResponseCreateGameSession.FromString,
                _registered_method=True)
        self.TerminateGameSession = channel.unary_unary(
                '/accelbyte.session.sessiondsm.SessionDsm/TerminateGameSession',
                request_serializer=session__dsm__pb2.RequestTerminateGameSession.SerializeToString,
                response_deserializer=session__dsm__pb2.ResponseTerminateGameSession.FromString,
                _registered_method=True)
        self.CreateGameSessionAsync = channel.unary_unary(
                '/accelbyte.session.sessiondsm.SessionDsm/CreateGameSessionAsync',
                request_serializer=session__dsm__pb2.RequestCreateGameSession.SerializeToString,
                response_deserializer=session__dsm__pb2.ResponseCreateGameSessionAsync.FromString,
                _registered_method=True)


class SessionDsmServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateGameSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TerminateGameSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateGameSessionAsync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SessionDsmServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateGameSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGameSession,
                    request_deserializer=session__dsm__pb2.RequestCreateGameSession.FromString,
                    response_serializer=session__dsm__pb2.ResponseCreateGameSession.SerializeToString,
            ),
            'TerminateGameSession': grpc.unary_unary_rpc_method_handler(
                    servicer.TerminateGameSession,
                    request_deserializer=session__dsm__pb2.RequestTerminateGameSession.FromString,
                    response_serializer=session__dsm__pb2.ResponseTerminateGameSession.SerializeToString,
            ),
            'CreateGameSessionAsync': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGameSessionAsync,
                    request_deserializer=session__dsm__pb2.RequestCreateGameSession.FromString,
                    response_serializer=session__dsm__pb2.ResponseCreateGameSessionAsync.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'accelbyte.session.sessiondsm.SessionDsm', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('accelbyte.session.sessiondsm.SessionDsm', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SessionDsm(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateGameSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accelbyte.session.sessiondsm.SessionDsm/CreateGameSession',
            session__dsm__pb2.RequestCreateGameSession.SerializeToString,
            session__dsm__pb2.ResponseCreateGameSession.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TerminateGameSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accelbyte.session.sessiondsm.SessionDsm/TerminateGameSession',
            session__dsm__pb2.RequestTerminateGameSession.SerializeToString,
            session__dsm__pb2.ResponseTerminateGameSession.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateGameSessionAsync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accelbyte.session.sessiondsm.SessionDsm/CreateGameSessionAsync',
            session__dsm__pb2.RequestCreateGameSession.SerializeToString,
            session__dsm__pb2.ResponseCreateGameSessionAsync.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
